# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
container_image = file:///projects/bacteriology_tran_data//binning_wf_containers/metabat2.sif

executable = ./scripts/02-generate_depths_maxbin2.sh
arguments = $(location) $(sample) $(sample_list)

# Include other files that need to be transferred here.

transfer_input_files = 02-generate_depths_maxbin2.sh
transfer_output_remaps = "$(sample)_vs_$(sample_list).depth.txt=file://$(location)/binning_wf/$(sample)/depths/$(sample)_vs_$(sample_list).depth.txt"

log = logs/depths_maxbin_$(sample)_$(cluster)_$(process).log
error = logs/depths_maxbin_$(sample)_$(cluster)_$(process).err
output = logs/depths_maxbin_$(sample)_$(cluster)_$(process).out

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 20
request_memory = 64GB
request_disk = 50GB      

queue sample_list from sample_list.txt
