
# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
#container_image = file:///projects/bacteriology_tran_data//binning_wf_containers/dastool.sif
container_image = oras://registry.doit.wisc.edu/ptran5/containers/dastool:1.1.7

executable = ./scripts/05-dastool.sh
arguments = $(location) $(sample) $(request_cpus)

# Include other files that need to be transferred here.
transfer_input_files = file://$(location)/binning_wf/$(sample)/bins/metabat2/$(sample)_metabat2_bins.tar.gz,file://$(location)/binning_wf/$(sample)/bins/maxbin2/$(sample)_maxbin2_bins.tar.gz,file://$(location)/preprocessing/assembly/$(sample)_scaffolds.fasta,file://$(location)/preprocessing/annotation/$(sample)_scaffolds_proteins.faa
transfer_output_files = $(sample)_refine_bins.tar.gz, $(sample)_refine_bins_DASTool_summary.tsv, $(sample)_refine_bins_DASTool_summary.tsv
transfer_output_remaps = "$(sample)_refine_bins.tar.gz=file://$(location)/binning_wf/$(sample)/bins/refined/$(sample)_refine_bins.tar.gz;$(sample)_refine_bins_DASTool_summary.tsv=file://$(location)/binning_wf/$(sample)/bins/refined/$(sample)_refine_bins_DASTool_summary.tsv"

log = logs/dastool_$(sample)_$(cluster)_$(process).log
error = logs/dastool_$(sample)_$(cluster)_$(process).err
output = logs/dastool_$(sample)_$(cluster)_$(process).out

# The correct syntax is to list then in one line, and use the double and (&&)
requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 20
request_memory = 16GB
request_disk = 50GB      

#queue sample from samples_colette.txt
queue
