
# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
container_image = file:///projects/bacteriology_tran_data//binning_wf_containers/dastool.sif

executable = ./scripts/05-dastool.sh
arguments = $(location) $(sample) $(request_cpus)

# Include other files that need to be transferred here.

transfer_input_files = 05-dastool.sh
transfer_output_remaps = "$(sample)_refine_bins.tar.gz=file://$(location)/binning_wf/$(sample)/bins/refined/$(sample)_refine_bins.tar.gz"

log = logs/dastool_$(sample)_$(cluster)_$(process).log
error = logs/dastool_$(sample)_$(cluster)_$(process).err
output = logs/dastool_$(sample)_$(cluster)_$(process).out

# The correct syntax is to list then in one line, and use the double and (&&)
requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 20
request_memory = 16GB
request_disk = 50GB      

#queue sample from samples_colette.txt
queue
