# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
# this checkm2 container is downloaded from the usegalaxy.org website.
#container_image = file:///projects/bacteriology_tran_data//binning_wf_containers/checkm2_1.0.1--pyh7cba7a3_0
#container_image = file:///projects/bacteriology_tran_data//binning_wf_containers/checkm2.sif
container_image = docker://staphb/checkm2:1.1.0

executable = ./scripts/06-checkm.sh
arguments = $(location) $(sample) $(request_cpus) $(db)

# Include other files that need to be transferred here.
transfer_output_files = $(sample)_checkm_out.tar.gz, checkm_out/quality_report.tsv
transfer_output_remaps = "$(sample)_checkm_out.tar.gz=file://$(location)/binning_wf/$(sample)/bins/QA/$(sample)_checkm_out.tar.gz;checkm_out/quality_report.tsv=file://$(location)/binning_wf/$(sample)/bins/QA/$(sample)_quality_report.tsv"

log = logs/checkm_$(sample)_$(cluster)_$(process).log
error = logs/checkm_$(sample)_$(cluster)_$(process).err
output = logs/checkm_$(sample)_$(cluster)_$(process).out

# make sure chtc projects is there because the Checkm database is there.
requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 20
request_memory = 16GB
request_disk = 50GB    

queue  

#queue sample from samples_colette.txt

