# apptainer.sub

# Provide HTCondor with the name of your .sif file and universe information
container_image = file:///projects/bacteriology_tran_data/binning_wf_containers/gtdbtk_v2.4.0.sif

executable = ./scripts/07-gtdbtk.sh
arguments = $(location) $(sample) $(request_cpus) $(db)

transfer_output_files = gtdb_output/gtdbtk.ar53.summary.tsv, gtdb_output/gtdbtk.bac120.summary.tsv, $(sample)_gtdbtk_output.tar.gz
transfer_output_remaps = "gtdb_output/gtdbtk.ar53.summary.tsv=file://$(location)/binning_wf/$(sample)/bins/taxonomy/gtdbtk.ar53.summary.tsv;gtdb_output/gtdbtk.bac120.summary.tsv=file://$(location)/binning_wf/$(sample)/bins/taxonomy/gtdbtk.bac120.summary.tsv;$(sample)_gtdbtk_output.tar.gz=file://$(location)/binning_wf/$(sample)/bins/taxonomy/$(sample)_gtdbtk_output.tar.gz"

log = logs/gtdbtk_$(sample)_$(cluster)_$(process).log
error = logs/gtdbtk_$(sample)_$(cluster)_$(process).err
output = logs/gtdbtk_$(sample)_$(cluster)_$(process).out

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 20
request_memory = 120GB
request_disk = 50GB      

queue
#queue
